name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync
        run: |
          curl -X POST "https://voila-api.mmopro.in/sync-app" \
            -H "Content-Type: application/json" \
            -d '{"app": "aiagent2oct27-1761566147357", "repo": "https://github.com/BharatSharma34/aiagent2oct27-1761566147357.git", "github_token": "${{ secrets.PRIVATE_GITHUB_TOKEN }}"}'